### ISSUE TITLE
Consider making Cauldron Crafter more compatible

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#20]
Either:
A: have it load its possible cauldrons from a csv so other modders can append their cauldrons
B: just do getequipmentlist excluding witchonly, excludefromrandomlists, and robotonly, shuffle that list, then iterate through it until you find an equipment whose last 8 characters are "Cauldron"

**Comment by JuniorUdale** [comment]
Done! `var eqlist = getequipmentlist(null|[]|[~witchonly~|~robotonly~|~excludefromrandomlists~|~alternateversion~]); var cauldrons = []; for(eq in eqlist){if(eq.indexOf(~Cauldron~) > -1){cauldrons.push(eq);};};` Bit more lenient since it checks if "cauldron" is in the name **anywhere**, but I'm sure that's fine.

**Comment by ncrecc** [comment]
Make sure also to apply this to Cauldron Cauldron (and Cauldron Crafter+, looks like you missed that one)

**Comment by JuniorUdale** [comment]
Whoops, done and done.
